---
on:
  push:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update && sudo apt upgrade -y
          sudo apt install ubuntu-drivers-common && sudo ubuntu-drivers install nvidia-driver-470
          sudo apt install cmake make g++ pkg-config libboost-all-dev linux-headers-$(uname -r) nvidia-cuda-toolkit
      - name: Build Application
        run: |
          cmake -S .
          cmake --build .
